# -----------------------------------------------------------
# Definitions
# -----------------------------------------------------------

stages:
  - Build
  - Variants

include:
  - project: "netify.ai/public/netify-development-support/\
              netify-ci-templates"
    ref: master
    file:
      - /gitlab/common/global-variables.yml
      - /gitlab/plugins/common-base-packages.yml
      - /gitlab/plugins/debian-base-packages.yml
      - /gitlab/plugins/rhel-base-packages.yml
      - /gitlab/plugins/build-templates.yml
      - /gitlab/common/variants-templates.yml

variables:
  NETIFY_MINVER: "5.0.4"
  NETIFY_VERREL:
    value: ${NETIFY_MINVER}-1
    expand: true
  GIT_SUBMODULE_STRATEGY: recursive
  EXTRA_PACKAGES_APT: >
    libcurl4-openssl-dev
    libmnl-dev
    libnetfilter-conntrack-dev
  EXTRA_PACKAGES_YUM: >
    curl-devel
    libmnl-devel
    libnetfilter_conntrack-devel

# -----------------------------------------------------------
# Build
# -----------------------------------------------------------

# Debian Targets

Debian/10/x86-64:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_NAME: "debian"
    OS_VERSION: "10"
    OS_IMAGE: "debian:10"
    OS_ARCH: "amd64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

Debian/11/x86-64:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_IMAGE: "debian:11"
    OS_ARCH: "amd64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

Debian/11/x86-32:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_IMAGE: "i386/debian:11"
    OS_ARCH: i386
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

Debian/11/ARM-32v5:
  extends: .debian_build
  when: manual
  tags:
    - docker
  variables:
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_IMAGE: "arm32v5/debian:11"
    OS_ARCH: "armel"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

Debian/11/ARM-32v7:
  extends: .debian_build
  when: manual
  tags:
    - docker
  variables:
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_IMAGE: "arm32v7/debian:11"
    OS_ARCH: "armhf"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

Debian/11/ARM-64v8:
  extends: .debian_build
  when: manual
  tags:
    - docker
  variables:
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_IMAGE: "arm64v8/debian:11"
    OS_ARCH: "arm64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

# Ubuntu Targets

Ubuntu/20.04/x86-64:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_NAME: "ubuntu"
    OS_VERSION: "focal"
    OS_IMAGE: "ubuntu:20.04"
    OS_ARCH: "amd64"
    OS_ARCH_PATH:
      value: "binary-$OS_ARCH"
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

Ubuntu/22.04/x86-64:
  extends: .debian_build
  tags:
    - docker
  variables:
    OS_NAME: "ubuntu"
    OS_VERSION: "jammy"
    OS_IMAGE: "ubuntu:22.04"
    OS_ARCH: "amd64"
    OS_ARCH_PATH:
      value: "binary-$OS_ARCH"
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true

# RedHat Targets

CentOS/7/x86-64:
  extends: .rhel_build
  when: manual
  tags:
    - docker
  variables:
    OS_NAME: "centos"
    OS_VERSION: "7"
    OS_IMAGE: "centos:7.9.2009"
    OS_ARCH: "x86_64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: ""
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_YUM
      expand: true

Rocky Linux/8/x86-64:
  extends: .rhel_build
  tags:
    - docker
  variables:
    OS_NAME: "rockylinux"
    OS_VERSION: "8"
    OS_IMAGE: "rockylinux:8"
    OS_ARCH: "x86_64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: "--enablerepo=powertools,epel"
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_YUM
      expand: true

AlmaLinux/8/x86-64:
  extends: .rhel_build
  tags:
    - docker
  variables:
    OS_NAME: "almalinux"
    OS_VERSION: "8"
    OS_IMAGE: "almalinux:8"
    OS_ARCH: "x86_64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: "--enablerepo=powertools,epel"
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_YUM
      expand: true

AlmaLinux/9/x86-64:
  extends: .rhel_build
  tags:
    - docker
  variables:
    OS_NAME: "almalinux"
    OS_VERSION: "9"
    OS_IMAGE: "almalinux:9"
    OS_ARCH: "x86_64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_REPOS: "--enablerepo=crb"
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_YUM
      expand: true

# -----------------------------------------------------------
# Variants
# -----------------------------------------------------------

# Source Code Archive

Source Archive:
  extends: .pkg_source
  tags:
    - docker
  needs:
    - Debian/11/x86-64
  variables:
    OS_NAME: "debian"
    OS_VERSION: "11"
    OS_IMAGE: "debian:11"
    OS_ARCH: "amd64"
    OS_ARCH_PATH:
      value: $OS_ARCH
      expand: true
    OS_EXTRA_PACKAGES:
      value: $EXTRA_PACKAGES_APT
      expand: true
